CREATE TABLE job_payment_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    assignment_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    payer_user_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(14,2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'KES',
    payment_method_id SMALLINT UNSIGNED NOT NULL,
    payment_intent_id BIGINT UNSIGNED NULL,
    status_id SMALLINT UNSIGNED NOT NULL,
    payment_reference VARCHAR(255) NULL,
    paid_at TIMESTAMP NULL,
    failed_at TIMESTAMP NULL,
    failure_reason VARCHAR(1000) NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_job_payment_records_public_id (public_id),
    UNIQUE KEY uq_job_payment_records_assignment (assignment_id),
    UNIQUE KEY uq_job_payment_records_idempotency (payer_user_id,idempotency_key),
    KEY idx_job_payment_records_job_status (job_id,status_id,created_at),
    KEY idx_job_payment_records_intent (payment_intent_id),
    KEY idx_job_payment_records_reference (payment_reference),
    CONSTRAINT fk_job_payment_records_assignment FOREIGN KEY (assignment_id) REFERENCES job_assignments(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_job_payment_records_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_job_payment_records_payer FOREIGN KEY (payer_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_job_payment_records_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_job_payment_records_intent FOREIGN KEY (payment_intent_id) REFERENCES payment_intents(id) ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_job_payment_records_status FOREIGN KEY (status_id) REFERENCES job_payment_statuses(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
