CREATE TABLE IF NOT EXISTS public_content (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    content_key VARCHAR(160) NOT NULL,
    locale VARCHAR(20) NOT NULL,
    content_type ENUM('text','json','number','boolean') NOT NULL DEFAULT 'text',
    content_value JSON NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_public_content_key_locale (content_key, locale),
    KEY idx_public_content_locale_active_order (locale, is_active, sort_order),
    CONSTRAINT chk_public_content_key_nonempty CHECK (CHAR_LENGTH(TRIM(content_key)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO public_content (content_key, locale, content_type, content_value, sort_order) VALUES
('navigation.home_aria','en-KE','text',JSON_QUOTE('Jijenge home'),10),
('navigation.home','en-KE','text',JSON_QUOTE('Home'),11),
('navigation.find_service','en-KE','text',JSON_QUOTE('Find a service'),12),
('navigation.providers_near_me','en-KE','text',JSON_QUOTE('Providers near me'),13),
('navigation.post_job','en-KE','text',JSON_QUOTE('Post a job'),14),
('navigation.notifications','en-KE','text',JSON_QUOTE('Notifications'),15),
('navigation.sign_in','en-KE','text',JSON_QUOTE('Sign in'),16),
('navigation.sign_out','en-KE','text',JSON_QUOTE('Sign out'),17),
('navigation.menu','en-KE','text',JSON_QUOTE('Open menu'),18),
('home.hero.eyebrow','en-KE','text',JSON_QUOTE('Built for your neighborhood'),100),
('home.hero.title','en-KE','text',JSON_QUOTE('Find the right hands for the job.'),101),
('home.hero.description','en-KE','text',JSON_QUOTE('Find skilled people nearby for the work you need done.'),102),
('home.hero.primary_action','en-KE','text',JSON_QUOTE('Explore services'),103),
('home.hero.secondary_action','en-KE','text',JSON_QUOTE('Find providers near me'),104),
('home.hero.card_label','en-KE','text',JSON_QUOTE('Local & verified'),105),
('home.hero.card_title','en-KE','text',JSON_QUOTE('People who know their craft.'),106),
('home.trust.title','en-KE','text',JSON_QUOTE('One useful place for local work.'),120),
('home.trust.items','en-KE','json',JSON_ARRAY('Verified providers','Clear categories','Real neighborhoods'),121),
('home.browse.eyebrow','en-KE','text',JSON_QUOTE('Browse'),140),
('home.browse.title','en-KE','text',JSON_QUOTE('Start with what you need.'),141),
('home.browse.description','en-KE','text',JSON_QUOTE('Search by service, browse by category, then find providers offering it near you.'),142),
('home.browse.callout_title','en-KE','text',JSON_QUOTE('Good work is closer than you think.'),143),
('home.browse.callout_description','en-KE','text',JSON_QUOTE('Share your location to see the best match nearby.'),144),
('home.browse.callout_action','en-KE','text',JSON_QUOTE('Find providers'),145),
('home.search.placeholder','en-KE','text',JSON_QUOTE('What needs doing?'),160),
('home.search.filters','en-KE','text',JSON_QUOTE('Filters'),161),
('home.search.filter_description','en-KE','text',JSON_QUOTE('Use a category to narrow your search.'),162),
('home.search.empty_title','en-KE','text',JSON_QUOTE('No services match that search yet.'),163),
('home.search.empty_description','en-KE','text',JSON_QUOTE('Try a broader phrase or another category.'),164),
('home.filters.all_services','en-KE','text',JSON_QUOTE('All services'),165),
('home.cta.eyebrow','en-KE','text',JSON_QUOTE('Make it happen'),180),
('home.cta.title','en-KE','text',JSON_QUOTE('A marketplace that speaks human.'),181),
('home.cta.description','en-KE','text',JSON_QUOTE('Clear categories, verified providers, and people building a good name one job at a time.'),182),
('home.cta.action','en-KE','text',JSON_QUOTE('Join Jijenge'),183),
('home.cta.note_label','en-KE','text',JSON_QUOTE('The Jijenge note'),184),
('home.cta.note_text','en-KE','text',JSON_QUOTE('Good work travels by word of mouth. We help it travel further.'),185),
('home.service_modal.find_providers','en-KE','text',JSON_QUOTE('Find providers for this'),200),
('footer.description','en-KE','text',JSON_QUOTE('Local work, made easier to find.'),220),
('footer.about','en-KE','text',JSON_QUOTE('About'),221),
('footer.safety','en-KE','text',JSON_QUOTE('Safety'),222),
('footer.support','en-KE','text',JSON_QUOTE('Support'),223),
('auth.messages.signed_out','en-KE','text',JSON_QUOTE('Signed out'),240),
('system.messages.coming_soon','en-KE','text',JSON_QUOTE('This flow is not available yet.'),250),
('system.errors.categories_load','en-KE','text',JSON_QUOTE('Could not load categories.'),251),
('system.errors.services_load','en-KE','text',JSON_QUOTE('Could not load services.'),252),
('system.errors.content_unavailable','en-KE','text',JSON_QUOTE('Site content is temporarily unavailable.'),253),
('system.actions.retry','en-KE','text',JSON_QUOTE('Retry'),254),
('system.actions.close','en-KE','text',JSON_QUOTE('Close'),255)
ON DUPLICATE KEY UPDATE content_type=VALUES(content_type), content_value=VALUES(content_value), is_active=VALUES(is_active), sort_order=VALUES(sort_order), updated_at=CURRENT_TIMESTAMP;
