import { ArrowRight, CheckCircle2, MapPin, Search, ShieldCheck, Star, Users, WalletCards } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { CategoryCard } from '../components/CategoryCard'
import { Link } from 'react-router-dom'
import { ServiceCard } from '../components/ServiceCard'
import { api } from '../lib/api'
import type { Branding, Service, ServiceCategory } from '../types'

export function HomePage({ branding }: { branding: Branding }) {
 const [categories,setCategories]=useState<ServiceCategory[]>([]), [services,setServices]=useState<Service[]>([]), [loading,setLoading]=useState(true), [error,setError]=useState('')
 useEffect(()=>{
  const controller=new AbortController()
  setLoading(true)
  setError('')
  Promise.all([api.categories(controller.signal),api.services(controller.signal)])
   .then(([categoryResponse,serviceResponse])=>{setCategories(categoryResponse||[]);setServices(serviceResponse.items||[])})
   .catch((err)=>{if(err?.name!=='AbortError')setError(err instanceof Error?err.message:'Unable to load marketplace data.')})
   .finally(()=>setLoading(false))
  return ()=>controller.abort()
 },[])
 const popular=useMemo(()=>services.slice(0,6),[services])
 return <main>
  <section className="overflow-hidden bg-slate-50"><div className="mx-auto grid max-w-7xl gap-12 px-5 pb-16 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pb-24 lg:pt-24">
   <div><div className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700"><span className="h-2 w-2 rounded-full bg-blue-600"/>A service marketplace built for you</div>
    <h1 className="mt-6 max-w-3xl text-5xl font-black tracking-tight text-slate-950 sm:text-6xl lg:text-7xl">Find services. <span className="text-blue-600">Offer your skills.</span> Get things done.</h1>
    <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Jijenge connects people who need services with skilled people who provide them. Whether you need help or have a skill to offer, one account lets you do both.</p>
    <form className="mt-8 flex max-w-2xl flex-col gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl shadow-slate-200/60 sm:flex-row" onSubmit={e=>e.preventDefault()}><div className="flex flex-1 items-center gap-3 px-3"><Search size={20} className="text-slate-400"/><input aria-label="Search services" className="w-full py-3 outline-none placeholder:text-slate-400" placeholder="What service do you need?"/></div><button className="rounded-xl bg-blue-600 px-7 py-3.5 font-bold text-white hover:bg-blue-700">Find a service</button></form>
    <div className="mt-6 flex flex-wrap gap-5 text-sm font-semibold text-slate-500"><span className="text-slate-700">Popular:</span>{services.slice(0,4).map(s=><Link key={s.id} to={`/services/${s.id}`} className="hover:text-blue-600">{s.name}</Link>)}{!loading && !error && services.length===0 && <span>No services available yet.</span>}{error && <span className="text-red-600">Services are temporarily unavailable.</span>}</div>
   </div>
   <div className="relative"><div className="rounded-[2rem] bg-slate-950 p-3 shadow-2xl"><div className="rounded-[1.5rem] bg-white p-6 sm:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">How Jijenge works</p><h2 className="mt-2 text-2xl font-black">One account. Two ways to use Jijenge.</h2></div><ShieldCheck className="text-blue-600"/></div><div className="mt-8 grid gap-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-blue-600"><Search size={19}/></span><div><b>Need a service?</b><p className="mt-1 text-sm text-slate-500">Discover providers, request work and track jobs.</p></div></div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-emerald-600"><Users size={19}/></span><div><b>Have a skill?</b><p className="mt-1 text-sm text-slate-500">Create a provider profile and receive opportunities.</p></div></div></div></div><div className="mt-5 flex items-center gap-2 text-sm font-semibold text-slate-500"><MapPin size={16} className="text-blue-600"/> Discover services around your location</div></div></div></div>
  </div></section>

  <section id="services" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-widest text-blue-600">Explore services</p><h2 className="mt-3 text-4xl font-black tracking-tight">What do you need help with?</h2><p className="mt-3 text-slate-500">Browse service categories and find people ready to help.</p></div>{loading?<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:8}).map((_,i)=><div key={i} className="h-44 animate-pulse rounded-2xl bg-slate-100"/>)}</div>:error?<div className="mt-10 rounded-2xl border border-red-100 bg-red-50 p-6 text-sm font-semibold text-red-700">{error}. Check VITE_API_BASE_URL and make sure the backend is reachable.</div>:categories.length>0?<div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((c,i)=><CategoryCard key={c.id} category={c} index={i}/>)}</div>:<div className="mt-10 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No service categories are available yet.</div>}</section>

  <section id="how-it-works" className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-widest text-blue-400">Simple process</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">From “I need help” to “job done.”</h2></div><div className="mt-12 grid gap-4 md:grid-cols-4">{[['01','Search','Tell us what service you need.'],['02','Discover','Find providers who match your needs and location.'],['03','Choose','Compare profiles, ratings and availability.'],['04','Get it done','Work with your provider from request to completion.']].map(([n,t,d])=><div key={n} className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><span className="text-sm font-black text-blue-400">{n}</span><h3 className="mt-12 text-xl font-bold">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{d}</p></div>)}</div></div></section>

  <section id="providers" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-black uppercase tracking-widest text-blue-600">For service providers</p><h2 className="mt-3 text-4xl font-black tracking-tight">Turn your skills into opportunities.</h2><p className="mt-4 max-w-xl leading-7 text-slate-500">You do not need a separate account. Start as a Jijenge user, then create your provider profile when you are ready to offer services.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{[['Create a profile',Users],['List your services',CheckCircle2],['Receive opportunities',Star],['Manage your earnings',WalletCards]].map(([t,I])=>{const Icon=I as typeof Users;return <div key={String(t)} className="flex items-center gap-3 rounded-xl border border-slate-200 p-4"><Icon size={19} className="text-blue-600"/><span className="font-semibold">{String(t)}</span></div>})}</div><Link to="/register" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3.5 font-bold text-white hover:bg-blue-700">Become a provider <ArrowRight size={18}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{popular.map(s=><ServiceCard key={s.id} service={s}/>)}</div></div></section>

  <section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8"><div className="rounded-[2rem] bg-blue-600 px-7 py-12 text-white sm:px-12 lg:flex lg:items-center lg:justify-between"><div className="max-w-2xl"><h2 className="text-3xl font-black sm:text-4xl">Ready to get started?</h2><p className="mt-3 text-blue-100">Create one free account and use Jijenge to find services, offer your skills, or do both.</p></div><div className="mt-7 flex flex-wrap gap-3 lg:mt-0"><Link to="/register" className="rounded-xl bg-white px-5 py-3.5 font-bold text-blue-700">Create account</Link><Link to="/services" className="rounded-xl border border-white/30 px-5 py-3.5 font-bold text-white">Browse services</Link></div></div></section>
 </main>
}
